// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl59sRmxoYoDK1SnWmiYqFRBYpzg3Y384',
    appId: '1:983598640244:web:5577fb831280888d9bb521',
    messagingSenderId: '983598640244',
    projectId: 'cclab-4ec42',
    authDomain: 'cclab-4ec42.firebaseapp.com',
    storageBucket: 'cclab-4ec42.firebasestorage.app',
    measurementId: 'G-EZE78WRHT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Foe24OHYm2OmW1K3QsvnpL2c1zzkURs',
    appId: '1:983598640244:android:60548d0ada68f95c9bb521',
    messagingSenderId: '983598640244',
    projectId: 'cclab-4ec42',
    storageBucket: 'cclab-4ec42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBetYEfnwLvDo7HxCFzDT70IHXuFeHxd5o',
    appId: '1:983598640244:ios:2d6222dc3c378e059bb521',
    messagingSenderId: '983598640244',
    projectId: 'cclab-4ec42',
    storageBucket: 'cclab-4ec42.firebasestorage.app',
    iosBundleId: 'com.cclab.withBible.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBetYEfnwLvDo7HxCFzDT70IHXuFeHxd5o',
    appId: '1:983598640244:ios:2d6222dc3c378e059bb521',
    messagingSenderId: '983598640244',
    projectId: 'cclab-4ec42',
    storageBucket: 'cclab-4ec42.firebasestorage.app',
    iosBundleId: 'com.cclab.withBible.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl59sRmxoYoDK1SnWmiYqFRBYpzg3Y384',
    appId: '1:983598640244:web:22a41f52f1ef918e9bb521',
    messagingSenderId: '983598640244',
    projectId: 'cclab-4ec42',
    authDomain: 'cclab-4ec42.firebaseapp.com',
    storageBucket: 'cclab-4ec42.firebasestorage.app',
    measurementId: 'G-GDEGHRKHR1',
  );
}
