default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Google Play"
  lane :internal do
    # Ensure the git status is clean, except in CI
    ensure_git_status_clean unless is_ci

    # Upload the AAB to Play Store
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_submission: true # Just upload, don't submit for review automatically
    )
  end

  desc "Distribute a new build to Firebase App Distribution"
  lane :firebase_dist do |options|
    firebase_app_distribution(
      app: "1:983598640244:android:60548d0ada68f95c9bb521",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: "service-account.json",
      groups: "testers",
      release_notes: options[:notes] || "Manual build"
    )
  end
end
