default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure the git status is clean
    ensure_git_status_clean

    # Increment build number (requires enabling Apple Generic Versioning in Xcode)
    # increment_build_number(xcodeproj: "Runner.xcodeproj")

    # Sync certificates and profiles (Read-only for CI/CD usually, but can be used locally)
    # match(type: "appstore", readonly: true)

    # Build the application
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
