// Mocks generated by Mockito 5.4.6 from annotations
// in with_bible/test/domain/usecases/create_group_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:with_bible/data/models/group_model.dart' as _i4;
import 'package:with_bible/data/models/user_model.dart' as _i6;
import 'package:with_bible/data/repositories/group_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GroupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupRepository extends _i1.Mock implements _i2.GroupRepository {
  MockGroupRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createGroup(_i4.GroupModel? group) =>
      (super.noSuchMethod(
            Invocation.method(#createGroup, [group]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createGroup, [group]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i4.GroupModel?> getGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroup, [groupId]),
            returnValue: _i3.Future<_i4.GroupModel?>.value(),
          )
          as _i3.Future<_i4.GroupModel?>);

  @override
  _i3.Future<void> joinGroup({
    required String? userId,
    required String? groupId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinGroup, [], {
              #userId: userId,
              #groupId: groupId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.UserModel>> getMembers({
    required String? groupId,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, [], {
              #groupId: groupId,
              #status: status,
            }),
            returnValue: _i3.Future<List<_i6.UserModel>>.value(
              <_i6.UserModel>[],
            ),
          )
          as _i3.Future<List<_i6.UserModel>>);

  @override
  _i3.Future<void> updateMemberStatus({
    required String? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemberStatus, [], {
              #userId: userId,
              #status: status,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.GroupModel>> getGroupsByChurch(String? churchId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroupsByChurch, [churchId]),
            returnValue: _i3.Future<List<_i4.GroupModel>>.value(
              <_i4.GroupModel>[],
            ),
          )
          as _i3.Future<List<_i4.GroupModel>>);
}
